### ISSUE TITLE
Clarification on risks

### ISSUE THREAD

**Issue by miketaylr** [WICG/web-smart-card#1]
In https://github.com/dandrader/web-smart-card/blob/main/README.md#risks, it talks about malicious websites - but this functionality is restricted to an installed Isolated Web App, correct? Is this a typo, or do I misunderstand how this might be abused?

**Comment by dandrader** [comment]
The document indeed recommends that this API is made available **only** to Isolated Web Apps. 
But the API is described independently from it. Thus the more generic term "website" being used instead of "isolated web app".

**Comment by dandrader** [comment]
Also the risks described there can be read as a justification for the recommendation of having the API available only to Isolated Web Apps.

**Comment by miketaylr** [comment]
Thanks, I see. It might be worth weaving some of that text into the explainer.
