### ISSUE TITLE
`SmartCardConnect::startTransaction` AbortSignal question

### ISSUE THREAD

**Issue by cmfcmf** [WICG/web-smart-card#31]
(split off of #30)

The `SmartCardConnect::startTransaction` API currently works like this:

```ts
type SmartCardDisposition =
  "leave" | "reset" | "unpower" | "eject";

const options = { signal: new AbortSignal() };

conn.startTransaction(async (): SmartCardDisposition | undefined => {
  await doSomeSmartCardStuff();
  return "reset";
}, options);
```

## How does the `AbortSignal` work?

If I am reading the [PC/SC spec](https://pcscworkgroup.com/Download/Specifications/pcsc5_v2.01.01.pdf) correctly, then `SCARDCOMM::Cancel()` cancels all transactions scheduled via `BeginTransaction()` that are not yet running (I might very well be wrong here though).

If I am reading the JS API spec proposed here correctly, then the `AbortSignal` passed in `options` to `startTransaction` will, if signalled, call `SCARDCOMM::Cancel()`, therefore cancelling _all_ pending transactions of this connection.

Example:

```ts
const controllerA = new AbortController();
const controllerB = new AbortController();

conn.startTransaction(async () => { // transaction A
  controllerA.signal(); // cancels pending transactions, in this case transaction B
}, { signal: controllerA.signal });

conn.startTransaction(async () => { // transaction B
  // Never runs, even though `controllerB.signal` is not signalled?
}, { signal: controllerB.signal });
```

If this is true, then I find the `AbortSignal` parameter a bit confusing. I would have expected it to only cancel the one transaction it is passed to, not all pending transactions. I'd rather have a separate method like "Cancel" or "CancelPendingTransactions" on `SmartCardConnection` to make this clearer.

(again, I might very well be misunderstanding how things work here)

**Comment by dandrader** [comment]
We have had similar discussions in the past (#10), even with a standalone `cancel()` [at some point](https://github.com/WICG/web-smart-card/pull/10/commits/819e1415959f9968956412ef33a5ae9c942db793).

In your example code, the second `startTransaction` method will immediately return a rejected Promise since multiple outstanding PC/SC operations in the same context are not supported and have undefined behavior in PC/SC implementations.

**Comment by cmfcmf** [comment]
Oh, I didn't realize this was the case. SGTM then.
