### ISSUE TITLE
Need clarification on getting started with the web-smart-card

### ISSUE THREAD

**Issue by tbensheimer** [WICG/web-smart-card#33]
When attempting to establish the context (navigator.smartCard.establishContext()), it gives an error "Cannot read properties of undefined (reading 'establishContext')". This might be because I have not done any configuring to my application.

I was hoping for more clarification/instructions on how to properly set up my application to get started. I was reading about the extensions and interfaces/webIDL and got a little confused.

**Comment by dandrader** [comment]
Hi @tbensheimer,

Thanks for your interest in trying it out.

I assume you're talking about the chrome implementation of that Web API. If so, I've written a demo application of it with instructions on how to get started and the setup needed:
https://github.com/GoogleChromeLabs/web-smartcard-demo

Note that the WICG/web-smart-card project is solely about the specification of this Web API and not about any browser implementation of it.
