### ISSUE TITLE
SmartCardTransactionCallback define problem? 

### ISSUE THREAD

**Issue by septs** [WICG/web-smart-card#34]
Specification use `() => Promise<SmartCardDisposition>` (TypeScript Syntax) define the callback

https://github.com/WICG/web-smart-card/blob/65e0d2f5389b6ff238de5c361a51045df72dead0/index.html#L930

But, example code in README file, then is `(connection: SmartCardConnection) => Promise<SmartCardDisposition | void>`

https://github.com/WICG/web-smart-card/blob/65e0d2f5389b6ff238de5c361a51045df72dead0/README.md?plain=1#L76

--------

Chromium IDL definitions the same as the specification

See https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/third_party/blink/renderer/modules/smart_card/smart_card_connection.idl#22

**Comment by septs** [comment]
https://github.com/NiceLabs/web-smartcard-types

**Comment by dandrader** [comment]
Fixed. Thanks for spotting that!
